# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_demo_apps do
    xcbuild(
      scheme: "Demo",
      xcargs: "-arch x86_64 -sdk iphonesimulator -showBuildTimingSummary",
      workspace: "Brightroom.xcworkspace",
    )

    xcbuild(
      scheme: "SwiftUIDemo",
      xcargs: "-arch x86_64 -sdk iphonesimulator -showBuildTimingSummary",
      workspace: "Brightroom.xcworkspace",
    )
  end

  lane :run_all_tests do
    scan(scheme: "BrightroomEngineTests")
  end
end
