import Foundation

/// Locates the package-owned general Core Image kernels for this platform.
///
/// These legacy Core Image libraries are compiled with `-fcikernel`. Keeping
/// them separate from the live brush shaders preserves the sampler ABI without
/// changing their compilation mode or compiling source at runtime. This module
/// is an implementation dependency of BrightroomParametric.
public enum ColorAdjustmentMetalLibrary {

  /// Reads the library generated by the package plugin or the host build rules.
  public static func data() throws -> Data {
    #if BRIGHTROOM_COLOR_ADJUSTMENTS_DEFAULT_LIBRARY
      // Tuist's external-package integration uses this target's Metal build
      // settings instead of executing SwiftPM build-tool plugins.
      let name = "default"
    #else
      #if targetEnvironment(macCatalyst)
        let platform = "catalyst"
      #elseif os(iOS)
        #if targetEnvironment(simulator)
          let platform = "simulator"
        #else
          let platform = "ios"
        #endif
      #elseif os(macOS)
        let platform = "macos"
      #else
        #error("Color adjustment kernels require iOS, Mac Catalyst, or macOS.")
      #endif

      let name = "BrightroomColorAdjustments-\(platform)"
    #endif
    guard let url = Bundle.module.url(forResource: name, withExtension: "metallib") else {
      throw ColorAdjustmentMetalLibraryError.missingResource(name)
    }
    return try Data(contentsOf: url)
  }
}

/// A required kernel library was not packaged with the kernel resource module.
public enum ColorAdjustmentMetalLibraryError: Error {
  case missingResource(String)
}
