# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BrightroomCocoaPodsInstallation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod "Brightroom/Engine", path: "../"
  pod "Brightroom/UI-Classic", path: "../"
  pod "Brightroom/UI-Crop", path: "../"
  # Pods for BrightroomCocoaPodsInstallation

end
