name: Cocoapods

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Force xcode 11.3
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - uses: actions/checkout@v2
    - name: Lint Cocoapods
      run: pod lib lint --allow-warnings
